name: Hello world
on: [workflow_dispatch]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      -run: python3 main.py